language: python
cache: pip

matrix:
  include:
  - python: 2.7
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
  - pip install -U pip setuptools wheel
  - pip install tox-travis

script: tox
